name: FirstAction

on: 
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]
    types: closed 

jobs:
  dockerpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependency project
        uses: actions/checkout@v3
        with:
          repository: appstics/lib-commons
          ref: develop 

      - name: Catch actual branch pom version
        shell: bash
        run: |
          echo "ACTUAL_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "APP_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV   

      - name: print vars
        run: |
          echo '${{env.ACTUAL_POM_VERSION}}'
          echo '${{env.APP_NAME}}'

      - name: Maven Build
        run: mvn clean install -f pom.xml

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: |
            👌Your image is compiled successfully with version ${{env.ACTUAL_POM_VERSION}}
            This the result at ${{env.APP_NAME}}